Добавлена возможность задавать конфигурацию тестового окружения АТОЛ
sputnik8/atol-rb pull request #13
Opened 2020-04-08 16:04 UTC by inner-whisper

## Изменения
- URL АТОЛа перенесен в конфигурацию (для удобства работы с тестовым окружением АТОЛ)
- В README добавлено описание подключения к тестовой среде в конфигурации

2020-04-08 16:09 UTC, inner-whisper commented
@GeorgeGorbanev я посмотрел, что работа над #11 немного затормозилась. 
В данном PR предлагаю свой вариант подключения к тестовому окружению.

2020-04-11 13:15 UTC, GeorgeGorbanev commented on README.md
> +АТОЛ предоставляет тестовую среду для отработки интеграции: их можно найти на странице https://online.atol.ru/lib/ по второй ссылке.
"их" не согласовано с другими частями предложения. Предлагаю немного переформулировать, добавить ссылку на сами данные для входа и сделать ссылки с разметкой.
```suggestion
АТОЛ предоставляет тестовую среду для отработки интеграции. Данные для авторизации в тестовой среде можно найти в [библиотеке документации АТОЛ Онлайн](https://online.atol.ru/lib/), пункт ["Параметры тестовой среды"](https://online.atol.ru/files/ffd/test_sreda.txt)
```

2020-04-11 13:22 UTC, GeorgeGorbanev commented on README.md
> +При передаче данных к тестовому API будьте аккуратны, чеки реально отправляются на почту.
Предлагаю добавить разметку и исключить слово "реально" чтобы выделить информацию и сделать язык более формальным
```suggestion
> _Внимание! При создании чеков в тестовой среде АТОЛ будет отправлять письма на электронную почту покупателя_
```

2020-04-11 13:32 UTC, GeorgeGorbanev commented on README.md
> +```ruby
Очень большой отрывок кода, который сильно похож на раздел "Конфигурация в инициализаторе" и данные в нем наверняка могут поменяться. Предлагаю убрать его или как-нибудь сослаться на тот раздел.

2020-04-11 13:33 UTC, GeorgeGorbanev commented on README.md
> +    # config.default_tax          = 'vat18'
Это немного запутывает, непонятно зачем в ридми закомментированные строки кода. Но как писал выше, думаю мы можем вообще убрать этот сниппет

2020-04-11 13:44 UTC, GeorgeGorbanev requested changes
Спасибо за ПР! Думаю, полезно, что по сравнению с решением в https://github.com/sputnik8/atol-rb/pull/11 можно указать любой урл. Это может пригодиться для е2е тестов, в которых поднят настоящий хттп-сервер имитирующий атол.

Написал несколько саджестов по поводу документации. Еще у нас пока нет code of conduct, но я все равно предлагаю вести историю изменений на английском языке. Давай сделаем название ПРа в духе: `feat: add config api url`

2020-04-16 09:52 UTC, inner-whisper commented on README.md
> +```ruby
Согласен. Убрал лишний кусок конфигурации, но добавил один пункт про указание `ATOL_API_URL`. Думаю, что без него будет сложно с ходу найти, как включить тестовый режим 😃

2020-04-16 09:52 UTC, inner-whisper commented on README.md
> +    # config.default_tax          = 'vat18'
Кусок кода удален

2020-04-16 09:58 UTC, inner-whisper commented
@GeorgeGorbanev 

Спасибо за ревью. Обработал все предложения по правкам.

> Это может пригодиться для е2е тестов, в которых поднят настоящий хттп-сервер имитирующий атол.

Dependency Injection дает свои неожиданные профиты 😃

2020-04-19 09:36 UTC, GeorgeGorbanev approved these changes
Все супер, спасибо за ПР! :)

2020-04-19 09:36 UTC, merged